biblioteca_django/biblioteca_django/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("biblioteca_django/", include("core.urls")),
]

biblioteca_django/core/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from .views import RegistroUsuarioView, AutorCreateView, MyLoginView
from .forms import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("inicio/", views.index, name="index"),
    path("Modificacion/AltaLibro", views.AltaLibro, name="altaLibro"),
    path("listaAutor/", views.listaAutor, name="listaAutor"),
    path("listaLibro/", views.listaLibro, name="listaLibro"),
    path("prestamos", views.v_prestamos, name="prestamos"),
    path("usuario/<int:user_id>/", views.usuario_perfil, name="usuario_perfil"),
    path("libro_detalle/<int:id_libro>/", views.libro_detalle, name="libro_detalle"),
    path("prestamos_form", views.prestamo_form, name="prestamos_form"),
    path("registro/", RegistroUsuarioView.as_view(), name="registro"),
    path("Modificacion/AltaAutor", AutorCreateView.as_view(), name="altaAutor"),
    path("resultados_busqueda/", views.resultados_busqueda, name="resultados_busqueda"),
    
    path("accounts/login/", MyLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("accounts/password_change/",auth_views.PasswordChangeView.as_view(template_name="core/registration/password_change_form.html"),name="password_change",),
    path("accounts/password_change/done/",auth_views.PasswordChangeDoneView.as_view(template_name="core/registration/password_change_done.html"),name="password_change_done",),
    path("accounts/password_reset/",auth_views.PasswordResetView.as_view(template_name="core/registration/password_reset_form.html"),name="password_reset",),
    path("accounts/password_reset/done/",auth_views.PasswordResetDoneView.as_view(template_name="core/registration/password_reset_done.html"),name="password_reset_done",),
    path("accounts/reset/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(template_name="core/registration/password_reset_confirm.html"),name="password_reset_confirm",),
    path("accounts/reset/done/",auth_views.PasswordResetCompleteView.as_view(template_name="core/registration/password_reset_complete.html"),name="password_reset_complete",),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biblioteca_django/core/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from datetime import timedelta
import re

GENRE_CHOICES = (
    ("FIC", "Ficción"),
    ("NFIC", "No Ficción"),
    ("SF", "Ciencia Ficción"),
    ("MYST", "Misterio"),
    ("ROM", "Romance"),
    ("DRAMA", "Drama"),
    ("FANT", "Fantasía"),
    ("BIO", "Biografía"),
    ("ACAD", "Artículos Académicos"),
)


class Usuario(AbstractUser):
    dni = models.IntegerField("DNI", unique=True, null=True, blank=True)

    def _str_(self):
        return f"{self.first_name} {self.last_name}"


class Autor(models.Model):
    nombre = models.CharField(
        max_length=100, verbose_name="Nombre y Apellido del Autor/a"
    )
    pais = models.CharField(max_length=100, verbose_name="Nacionalidad del Autor/a")
    nacimiento = models.IntegerField(verbose_name="Año de nacimiento del Autor/a")

    def __str__(self):
        return self.nombre


class Libro(models.Model):
    autores = models.ManyToManyField(Autor, verbose_name="Autor/a o Autor@s del Libro")
    titulo = models.CharField(max_length=255, verbose_name="Título del Libro")
    editorial = models.CharField(max_length=255, verbose_name="Editorial")
    publicacion = models.IntegerField(verbose_name="Año de publicación")
    genero = models.CharField(max_length=100, choices=GENRE_CHOICES)
    imagen = models.ImageField(upload_to="media/", default="default_book_cover.png")

    def __str__(self):
        return self.titulo


class Prestamo(models.Model):
    usuario = models.ForeignKey(
        Usuario, on_delete=models.CASCADE, verbose_name="Usuario"
    )
    libro = models.ForeignKey(
        Libro, on_delete=models.CASCADE, verbose_name="Libro Prestado"
    )
    fecha_prestamo = models.DateField(verbose_name="Fecha de Préstamo")
    fecha_devolucion = models.DateField(verbose_name="Fecha de Devolución")

    def save(self, *args, **kwargs):
        if not self.fecha_devolucion:
            self.fecha_devolucion = self.fecha_prestamo + timedelta(days=14)
        super(Prestamo, self).save(*args, **kwargs)

    def __str__(self):
        return f"Prestamo de {self.libro} a {self.usuario} retirado {self.fecha_prestamo} devolucion {self.fecha_devolucion}"

biblioteca_django/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from core.forms import *
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .models import Prestamo, Autor, Libro
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
import logging

logging.basicConfig(level=logging.DEBUG)


# ---------------------------------------------------------------------------------------------------------------------------------
class RegistroUsuarioView(CreateView):
    form_class = RegistroUsuarioForm
    success_url = reverse_lazy("login")
    template_name = "core/registro.html"

    def form_valid(self, form):
        messages.success(self.request, "Te has registrado exitosamente!")
        return super(RegistroUsuarioView, self).form_valid(form)


# ---------------------------------------------------------------------------------------------------------------------------------


def prestamo_form(request):
    if request.method == "POST":
        form_prestamo = PrestamoForm(request.POST)

        if form_prestamo.is_valid():
            try:
                libro = form_prestamo.cleaned_data["id_libro"]
                id = request.POST.get("id_libro")
                libro = Libro.objects.get(id=id)

                usuario = form_prestamo.cleaned_data["nombre_usuario"]
                nuevo_prestamo = Prestamo(
                    libro=libro,
                    usuario=usuario,
                    fecha_prestamo=form_prestamo.cleaned_data["fecha_prestamo"],
                )
                nuevo_prestamo.save()
                messages.info(request, "El préstamo fue guardado correctamente")
                return redirect(reverse("prestamos"))

            except Libro.DoesNotExist:
                messages.error(request, "No se encontró el libro")
            except Usuario.DoesNotExist:
                messages.error(request, "No se encontró el usuario")
            except IntegrityError as e:
                messages.error(request, str(e))

            return redirect(reverse("prestamos"))
        else:
            errores = form_prestamo.errors
            return render(
                request,
                "core/prestamos.html",
                {"form": form_prestamo, "errores": errores},
            )
    else:
        form = PrestamoForm()
        return render(request, "core/prestamos.html", {"form": form})


# ---------------------------------------------------------------------------------------------------------------------------------


def index(request):
    return render(request, "core/index.html")


# ---------------------------------------------------------------------------------------------------------------------------------


def AltaLibro(request):
    if request.method == "POST":
        FormularioAlta = AltaLibroForm(request.POST, request.FILES)
        if FormularioAlta.is_valid():  
            numero = FormularioAlta.cleaned_data["cantidad"]
            for i in range(1, numero + 1):
                FormularioAlta.save()
                FormularioAlta = AltaLibroForm(request.POST, request.FILES)
            messages.info(request, "Su operacion fue ejecutada con exito")
            return redirect(reverse("altaLibro"))
    else:
        FormularioAlta = AltaLibroForm()

    context = {"altaLibro_form": FormularioAlta}

    return render(request, "core/altaLibro.html", context)


# ---------------------------------------------------------------------------------------------------------------------------------


def libro_detalle(request, id_libro):
    # Use get_object_or_404 to retrieve the Libro object or return a 404 error if not found
    libro = get_object_or_404(Libro, pk=id_libro)

    return render(request, "core/libro_detalle.html", {"libro": libro})


# ---------------------------------------------------------------------------------------------------------------------------------
def listaAutor(request):
    autores = Autor.objects.all()
    return render(request, "core/listaAutor.html", {"autores": autores})


# ---------------------------------------------------------------------------------------------------------------------------------


def listaLibro(request):
    libros = Libro.objects.all()
    return render(request, "core/listaLibro.html", {"libros": libros})


# ---------------------------------------------------------------------------------------------------------------------------------


def v_prestamos(request):
    lst_prestamos = Prestamo.objects.all()
    prestamos = []
    for p in lst_prestamos:
        prestamos.append(
            [
                p.libro.titulo,
                p.usuario.first_name + " " + p.usuario.last_name,
                p.fecha_prestamo,
            ]
        )

    form_prestamo = PrestamoForm()
    context = {
        "prestamos": prestamos,
        "form": form_prestamo,
    }

    return render(request, "core/prestamos.html", context)


# ---------------------------------------------------------------------------------------------------------------------------------


class AutorCreateView(CreateView):
    model = Autor
    form_class = altaAutor
    template_name = "core/altaAutor.html"
    success_url = reverse_lazy("altaAutor")

    def form_valid(self, form):
        messages.success(self.request, "Autor creado con éxito.")
        return super(AutorCreateView, self).form_valid(form)


# ---------------------------------------------------------------------------------------------------------------------------------


class MyLoginView(LoginView):
    template_name = "core/registration/login.html"

    def form_valid(self, form):
        messages.success(self.request, "Inicio de sesión exitoso.")
        return super().form_valid(form)


# ---------------------------------------------------------------------------------------------------------------------------------

# VISTA DE USUARIO Y SUS LIBROS PRESTADOS


@login_required
def usuario_perfil(request, user_id):
    user = get_object_or_404(Usuario, id=user_id)
    libros_prestados = request.user.prestamo_set.all()

    return render(
        request,
        "core/usuario_perfil.html",
        {"libros_prestados": libros_prestados, "user": user},
    )


# ---------------------------------------------------------------------------------------------------------------------------------


def resultados_busqueda(request):
    form = Buscador(request.GET or None)
    results = {
        "autor_results": Autor.objects.none(),
        "libro_results": Libro.objects.none(),
    }

    if request.GET and form.is_valid():
        busqueda = form.cleaned_data["busqueda"]
        logging.debug(f"Search Query: {busqueda}")

        logging.debug(f"Form Data: {form.cleaned_data}")

        autor_results = Autor.objects.filter(nombre__icontains=busqueda)
        libro_results = Libro.objects.filter(titulo__icontains=busqueda)
        results = {
            "autor_results": autor_results,
            "libro_results": libro_results,
        }

        logging.debug(f"Autores: {autor_results.count()}")
        logging.debug(f"Libros: {libro_results.count()}")

    return render(
        request, "core/resultados_busqueda.html", {"form": form, "results": results}
    )


# ---------------------------------------------------------------------------------------------------------------------------------

biblioteca_django/core/templates/core/altaAutor.html
{% extends "core/base.html" %}
{% load static %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'core/css/form.css' %}"> 
{% endblock %}
{% block title %} Alta Autor {% endblock %}
{% block section_title %}Carga de Autor{% endblock %}
{% block content %}
{% if messages %}
<ul class="messages">
  {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}" {% endif %}> {{ message }}</li>
  {% endfor %}
</ul>
{% endif %}



<form method="post" action="{% url 'altaAutor' %}">
    {% csrf_token %}
    <div class="formularioModificacion">
      <h2 class="formulario_titulo">Carga de Autor</h2>
      {{form.as_p}}
      <input type="submit" value="Crear" class="boton">
    </div>   
</form>
   
{% endblock %}

    
   

biblioteca_django/core/templates/core/altaLIbro.html
{% extends "core/base.html" %}
{% load static %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'core/css/form.css' %}"> 
{% endblock %}
{% block title %} Alta Libro {% endblock %}
{% block section_title %}Carga de libro{% endblock %}
{% block content %}
{% if messages %}
<ul class="messages">
  {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}" {% endif %}> {{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

<form method="post" action="{% url 'altaLibro' %}" enctype="multipart/form-data"> {% comment %} necesitamos este atributo para cargar la caratula {% endcomment %}
    {% csrf_token %}
    <div class="formularioModificacion">
      <h2 class="formulario_titulo">Carga de Libro</h2>
      <div id="selected_authors"></div>
          {{altaLibro_form}}
      <input type="submit" value="Crear" class="boton">
    </div>   
</form>

<script>
  document.addEventListener('DOMContentLoaded', function() {
      const autorField = document.querySelector('#id_autores');
      const selectedAuthorsContainer = document.querySelector('#selected_authors');

      autorField.addEventListener('change', function() {
          const selectedAuthors = [];
          for (let i = 0; i < autorField.options.length; i++) {
              if (autorField.options[i].selected) {
                  selectedAuthors.push(autorField.options[i].text);
              }
          }
          selectedAuthorsContainer.textContent = `Selected authors: ${selectedAuthors.join(', ')}`;
      });
  });
</script>
{% endblock %}

    
   

biblioteca_django/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biblioteca Django - {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'core/css/base.css' %}">
    {% block extra_css %}{% endblock %}
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <div class="navbar-nav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'index' %}">Inicio</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Libros
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'listaLibro' %}">Lista de Libros</a></li>
                                {% if request.user.is_staff or request.user.is_superuser %}
                                    <li><a class="dropdown-item" href="{% url 'altaLibro' %}">Carga de Libro</a></li>

                                {% endif %}
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Autores
                            </a>
                            <ul class="dropdown-menu">
                                {% if request.user.is_staff or request.user.is_superuser %}
                                    <li><a class="dropdown-item" href="{% url 'altaAutor' %}">Alta de Autores</a></li>
                                {% endif %}
                                <li><a class="dropdown-item" href="{% url 'listaAutor' %}">Lista de Autores</a></li>
                            </ul>
                        </li>

                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'prestamos' %}">Préstamos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'usuario_perfil' user_id=request.user.id %}">Perfil de usuario</a>
                        </li>
                        <div class="ml-auto">
                            <li class="nav-item"> 
                                <a class="nav-link" href="{% url 'logout' %}">
                                    <button class="btn btn-success">Cerrar Sesión</button>
                                </a>
                            </li>
                        </div>
                    {% endif %}
                    
                    </ul>
                </div>

                {% if not request.user.is_authenticated %}
                    <div class="navbar-nav ml-auto">
                        <ul class="navbar-nav"> 
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'registro' %}">
                                    <button class="btn" style="background-color: #3f9a78; color: white;">Registro</button>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}">
                                    <button class="btn btn-success">Iniciar Sesión</button>
                                </a>
                            </li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </nav>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </header>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-12">
                <h1>{% block page_title %}{% endblock %}</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 text-center">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    {% include "core/footer.html" %}
                </div>
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

biblioteca_django/core/templates/core/footer.html
<footer>
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy; Biblioteca Django. Todos los derechos reservados.</p>
        </div>
        <div class="col-md-6 text-right">
          <p>Grupo 9 - Codo a Codo 2023</p>
        </div>
      </div>
    </div>
</footer>
  

biblioteca_django/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div class="mt-5">
  <h1 class="text-center mb-3">Bienvenido a la Biblioteca</h1>

  <form method="GET" action="{% url 'resultados_busqueda' %}" class="text-center">
    {% csrf_token %}
    <div class="form-group mb-3">
      <input type="text" name="busqueda" placeholder="Buscar en nuestro catálogo por libro o autor" class="form-control dark-input" style="width: 60%; margin: 0 auto;">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-success btn-block" style="width: 20%;">Buscar</button>
    </div>
  </form>
</div>
{% endblock %}

biblioteca_django/core/templates/core/libro_detalle.html
{% extends "core/base.html" %}
{% load static %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'core/css/libro_detalle.css' %}"> 
{% endblock %}
{% block title %}{{ libro.titulo }}{% endblock %}

{% block content %}
<div class="libro-grid"> <div class="portada">
<img src="{{ libro.imagen.url }}" alt="Portada del libro: {{ libro.titulo }}" /></div>
<div class="info-basica">
  <h1>{{ libro.titulo }}</h1>
  <p>Autores:
    {% for autor in libro.autores.all %}
        {{ autor.nombre }}{% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
  <p>Editorial: {{ libro.editorial }}</p>
  <p>Año de publicación: {{ libro.publicacion }}</p>
  <p>Género: {{ libro.get_genero_display }}</p>
</div> <div class="detalles"> --------------------------------------</div></div>


{% endblock %}

biblioteca_django/core/templates/core/listaAutor.html
{% extends "core/base.html" %}
{% load static %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'core/css/modificacionLibro.css' %}"> 
{% endblock %}
{% block title %} Ver Autores {% endblock %}

{% block content %}
<h1>Lista de Autores</h1>
<table class="table table-dark table-hover rounded-10 overflow-hidden">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre y Apellido</th>
        <th scope="col">Nacionalidad</th>
        <th scope="col">Año de Nacimiento</th>
      </tr>
    </thead>
    <tbody>

        {% for autor in autores %}
        <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ autor.nombre }}</td>
        <td>{{ autor.pais }}</td>
        <td>{{ autor.nacimiento }}</td>
        </tr>
        {% endfor %}
    
    </tbody>
  </table>
    

{% endblock %}

biblioteca_django/core/templates/core/listaLibro.html
{% extends "core/base.html" %}
{% load static %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'core/css/listados.css' %}"> 
{% endblock %}
{% block title %} Ver Autores {% endblock %}

{% block content %}
<h1>Lista de Libros</h1>
<table class="table table-dark table-hover rounded-10 overflow-hidden">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Titulo</th>
            <th scope="col">Autor/a o Autor@s</th>
            <th scope="col">Editorial</th>
            <th scope="col">Año de publicación</th>
            <th scope="col">Género</th>
        </tr>
    </thead>
    <tbody>
        {% for libro in libros %}
            <tr onclick="window.location='{% url 'libro_detalle' libro.id %}'" style="cursor:pointer;">
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ libro.titulo }}</td>
                <td>
                    {% for autor in libro.autores.all %}
                        {{ autor.nombre }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
                <td>{{ libro.editorial }}</td>
                <td>{{ libro.publicacion }}</td>
                <td>{{ libro.genero }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

biblioteca_django/core/templates/core/prestamos.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
{% load static %}
{% block extra_css%}
    <link rel="stylesheet" href="{% static 'core/css/form.css' %}">
{%endblock%}
<body>
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}> {{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}  
  <div class="formularioModificacion">
  <h1>Préstamo de Libros</h1>
  <form method="post" action="{% url 'prestamos_form' %}">
    {% csrf_token %}
  
    <!-- Campo Título del Libro -->
    <div>
        {{ form.titulo.label_tag }}
        {{ form.titulo }}
        {{ form.titulo.errors }}
    </div>

    <!-- Campo Autor -->
    <div>
        {{ form.autor.label_tag }}
        {{ form.autor }}
        {{ form.autor.errors }}
    </div>

    <div>
      {{ form.id_libro.label_tag }}
      {{ form.id_libro }}
      {{ form.id_libro.errors }}
  </div>
    <!-- Campo Nombre del Usuario -->
    <div>
        {{ form.nombre_usuario.label_tag }}
        {{ form.nombre_usuario }}
        {{ form.nombre_usuario.errors }}
    </div>

    <div>
      {{ form.id_usuario.label_tag }}
      {{ form.id_usuario }}
      {{ form.id_usuario.errors }}
  </div>
 <!-- Campo Fecha de Préstamo -->
 <div>
  {{ form.fecha_prestamo.label_tag }}
  {{ form.fecha_prestamo }}
  {{ form.fecha_prestamo.errors }}
</div>

    <!-- Botón de Enviar -->
    <div>
        <input type="submit" value="Enviar">
    </div>
</form>
   
</div>
  <!-- Lista de préstamos existentes -->
  <h2>Préstamos Actuales</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Libro</th>
        <th>Usuario</th>
        <th>Fecha de Préstamo</th>
      </tr>
    </thead>
    <tbody>
      {% for prestamo in prestamos %}
      {% filter  upper %}
        <tr>
          <td>{{ prestamo.0 }}</td>
          <td>{{ prestamo.1 }}</td>
          <td>{{ prestamo.2 }}</td>
         
        </tr>
        {% endfilter %}
       
      {% empty %}
        <tr>
          <td colspan="3">No hay préstamos registrados.</td>
        </tr>
      
      {% endfor %}
    </tbody>
  </table>
</body>
{% endblock %}

biblioteca_django/core/templates/core/registro.html
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'core/css/base.css' %}">
<link rel="stylesheet" href="{% static 'core/css/login.css' %}">
{% endblock %}
{% block extra_js %}
<script src="{% static 'core/js/main.js' %}"></script>
{% endblock %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}> {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<body>


    <div class="login-container">
        <form method="post">
            <h2>Registro de Usuario</h2>
            {% csrf_token %}

            {% if form.non_field_errors %}
                <ul class="errorlist hidden"> <!-- Añade la clase hidden aquí -->
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}


            {{ form.as_table }}  
            <input type="submit" value="Registrar"></button>
        </form>
    </div>
</body>

{% endblock %}

biblioteca_django/core/templates/core/resultados_busqueda.html
{% extends "core/base.html" %}
{% load static %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'core/css/listados.css' %}"> 
{% endblock %}
{% block title %} Ver Autores {% endblock %}

{% block content %}
<form method="GET">
    {{ form.as_p }}
    <button type="submit">Buscar</button>
</form>

<h2>Autores</h2>
<ul class="resultados_busqueda">
    {% for author in results.autor_results %}
        <li>{{ author.nombre }}</li>
    {% empty %}
        <li>No se encontraron autores con ese nombre.</li>
    {% endfor %}
</ul>

<h2>Libros</h2>
<ul class="resultados_busqueda">
    {% for book in results.libro_results %}
        <li>{{ book.titulo }}</li>
    {% empty %}
        <li>No se encontraron libros con ese nombre.</li>
    {% endfor %}
</ul>
{% endblock %}

biblioteca_django/core/templates/core/usuario_perfil.html
{% extends "core/base.html" %}

{% load static %}

{% block title %} Mi perfil {% endblock %}

{% block content %}
    <h2><b>Perfil de Usuario - </b>{{ user.username }} </h2>
    <p>ID de Usuario: {{ user.id }}</p>
    <p>Nombre Completo: {{ user.get_full_name }}</p>
    
    <h3>Libros Prestados</h3>
    {% if user.libros_prestados.all %}
        <ul>
            {% for libro in user.libros_prestados.all %}
                <li>{{ libro.titulo }} por {{ libro.autores.all|join:", " }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No se han prestado libros aún.</p>
    {% endif %}

{% endblock %}